// SPDX-FileCopyrightText: 2026 SecPal Contributors
// SPDX-License-Identifier: MIT
import assert from 'assert'
import * as crypto from 'crypto'
import * as fs from 'fs'
import * as path from 'path'

const outDir = path.join(process.cwd(), 'out')
const trackedSnippetPath = path.join(
  process.cwd(),
  'nginx',
  'changelog-csp.conf',
)
const generatedSnippetPath = path.join(
  outDir,
  'nginx',
  'changelog-csp.conf',
)

const cspPrefix = [
  "default-src 'self'",
  "base-uri 'self'",
  "connect-src 'self' https:",
  "font-src 'self' data:",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "frame-src 'none'",
  "img-src 'self' data: blob:",
  "manifest-src 'self'",
  "media-src 'self'",
  "object-src 'none'",
]

const cspSuffix = [
  "script-src-attr 'none'",
  "style-src 'self' 'unsafe-inline'",
  "style-src-elem 'self'",
  "style-src-attr 'unsafe-inline'",
  "worker-src 'self'",
  'upgrade-insecure-requests',
]

function walkHtmlFiles(directory) {
  return fs
    .readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const fullPath = path.join(directory, entry.name)

      if (entry.isDirectory()) {
        return walkHtmlFiles(fullPath)
      }

      return entry.isFile() && fullPath.endsWith('.html') ? [fullPath] : []
    })
    .sort()
}

function collectInlineScriptHashes(htmlFilePath) {
  const html = fs.readFileSync(htmlFilePath, 'utf8')
  const hashes = []

  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    const attributes = match[1]
    const body = match[2]

    if (/\bsrc\s*=/.test(attributes) || body.length === 0) {
      continue
    }

    hashes.push(
      `sha256-${crypto.createHash('sha256').update(body).digest('base64')}`,
    )
  }

  return hashes
}

function renderSnippet(hashes) {
  const directives = [
    ...cspPrefix,
    `script-src 'self' ${hashes.join(' ')}`,
    ...cspSuffix,
  ]

  const snippetHeader = [
    '# SPDX-FileCopyrightText: 2026 SecPal',
    `# SPDX-${'License-Identifier'}: CC0-1.0`,
    '# Generated by scripts/generate-csp.mjs from out/**/*.html',
  ]

  return [
    ...snippetHeader,
    `set $secpal_csp "${directives.join('; ')}";`,
    '',
  ].join('\n')
}

function writeFile(targetPath, contents) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true })
  fs.writeFileSync(targetPath, contents)
}

assert(fs.existsSync(outDir), `Build output missing: ${outDir}. Run 'npm run build' first.`)

const htmlFiles = walkHtmlFiles(outDir)
assert(htmlFiles.length > 0, `No exported HTML files found in ${outDir}.`)

const hashes = [...new Set(htmlFiles.flatMap(collectInlineScriptHashes))].sort()
assert(hashes.length > 0, 'No inline scripts found in exported HTML.')

const snippet = renderSnippet(hashes)
writeFile(generatedSnippetPath, snippet)

if (process.argv.includes('--check')) {
  if (!fs.existsSync(trackedSnippetPath)) {
    console.error(
      `Tracked CSP snippet missing: ${trackedSnippetPath}. Run 'npm run csp:update'.`,
    )
    process.exit(1)
  }

  const trackedSnippet = fs.readFileSync(trackedSnippetPath, 'utf8')

  if (trackedSnippet !== snippet) {
    console.error(
      `Tracked CSP snippet is stale: ${trackedSnippetPath}. Run 'npm run csp:update'.`,
    )
    process.exit(1)
  }
}

if (process.argv.includes('--write')) {
  writeFile(trackedSnippetPath, snippet)
}

console.log(
  `Generated CSP snippet with ${hashes.length} inline script hashes from ${htmlFiles.length} HTML files.`,
)
console.log(`Build artifact: ${generatedSnippetPath}`)

if (process.argv.includes('--write')) {
  console.log(`Updated tracked snippet: ${trackedSnippetPath}`)
}
